import{a as d,S as g,i as u}from"./assets/vendor-C9g_EN52.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const o of a.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&l(o)}).observe(document,{childList:!0,subtree:!0});function r(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function l(e){if(e.ep)return;e.ep=!0;const a=r(e);fetch(e.href,a)}})();d.defaults.baseURL="https://pixabay.com/api";const f={key:"19987924-b7a96d980a74a373c9da34c4a",image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:18,q:""};function y(t){return f.q=t,d.get("",{params:f}).then(s=>s.data).catch(s=>console.log(s))}const n={gallery:document.querySelector(".gallery"),loader:document.querySelector(".js-loader")},p=new g(".gallery a",{overlayOpacity:.8,captions:!0,captionsData:"alt",captionDelay:100,captionPosition:"bottom"});p.on("error.simplelightbox",function(t){console.log(t)});function h(){n.loader.classList.add("active")}function v(){n.loader.classList.remove("active")}function L(){n.gallery.innerHTML=""}function b({id:t,webformatURL:s,largeImageURL:r,likes:l,views:e,comments:a,downloads:o,tags:m}){return`<li class="gallery-item" data-id=${t}>
  <a class="gallery-link" href="${r}">
  <div class="image-wrapper">
        <img class="gallery-image" src="${s}" alt="${m}" /></div>
       <ul class='statistics'>
        <li><span class="statistics-label">likes</span><span class="statistics-value">${l}</span></li>
        <li><span class="statistics-label">views</span><span class="statistics-value">${e}</span></li>
        <li><span class="statistics-label">comments</span><span class="statistics-value">${a}</span></li>
        <li><span class="statistics-label">downloads</span><span class="statistics-value">${o}</span></li>
       </ul>  
    </a>
    </li>`}function S(t){return t.map(b).join("")}function w(t){const s=S(t);n.gallery.innerHTML=s,p.refresh()}const i={formEle:document.querySelector(".form")};i.formEle.addEventListener("submit",t=>{t.preventDefault(),L();const s=i.formEle.elements["search-text"].value.trim();if(!s){c.show("noSearchParams");return}h(),y(s).then(r=>{r.total?w(r.hits):c.show("notFound")}).finally(()=>{v()}),i.formEle.reset()});i.formEle.addEventListener("click",t=>{t.target.nodeName==="INPUT"&&c.close()});const c={message:{noSearchParams:"Please fill out input field.",notFound:"Sorry, there are no images matching your search query. Please, try again!"},show(t){u.show({message:this.message[t],position:"topRight",backgroundColor:"#EF4040",messageColor:"#ffffff",iconUrl:"./img/x-octagon.svg",timeout:1e4,closeOnClick:!0})},close(){try{u.hide({},document.querySelector(".iziToast"))}catch{}}};
//# sourceMappingURL=index.js.map
