import{a as d,S as g,i as u}from"./assets/vendor-C9g_EN52.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const o of a.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&i(o)}).observe(document,{childList:!0,subtree:!0});function r(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function i(t){if(t.ep)return;t.ep=!0;const a=r(t);fetch(t.href,a)}})();d.defaults.baseURL="https://pixabay.com/api";const f={key:"19987924-b7a96d980a74a373c9da34c4a",image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:18,q:""};function y(e){return f.q=e,d.get("",{params:f}).then(s=>s.data).catch(s=>n(s))}const c={gallery:document.querySelector(".gallery"),loader:document.querySelector(".js-loader")},p=new g(".gallery a",{overlayOpacity:.8,captions:!0,captionsData:"alt",captionDelay:100,captionPosition:"bottom"});p.on("error.simplelightbox",function(e){console.log(e)});function h(){c.loader.classList.add("active")}function v(){c.loader.classList.remove("active")}function L(){c.gallery.innerHTML=""}function b({id:e,webformatURL:s,largeImageURL:r,likes:i,views:t,comments:a,downloads:o,tags:m}){return`<li class="gallery-item" data-id=${e}>
  <a class="gallery-link" href="${r}">
  <div class="image-wrapper">
        <img class="gallery-image" src="${s}" alt="${m}" /></div>
       <ul class='statistics'>
        <li><span class="statistics-label">likes</span><span class="statistics-value">${i}</span></li>
        <li><span class="statistics-label">views</span><span class="statistics-value">${t}</span></li>
        <li><span class="statistics-label">comments</span><span class="statistics-value">${a}</span></li>
        <li><span class="statistics-label">downloads</span><span class="statistics-value">${o}</span></li>
       </ul>  
    </a>
    </li>`}function S(e){return e.map(b).join("")}function w(e){const s=S(e);c.gallery.innerHTML=s,p.refresh()}const l={formEle:document.querySelector(".form")};l.formEle.addEventListener("submit",e=>{e.preventDefault(),L();const s=l.formEle.elements["search-text"].value.trim();if(!s){n.show("noSearchParams");return}h(),y(s).then(r=>{r.total?w(r.hits):n.show("notFound")}).finally(()=>{v()}),l.formEle.reset()});l.formEle.addEventListener("click",e=>{e.target.nodeName==="INPUT"&&n.close()});const n={message:{noSearchParams:"Please fill out input field.",notFound:"Sorry, there are no images matching your search query. Please, try again!"},show(e){const s=this.message[e]?this.message[e]:e;u.show({message:s,position:"topRight",backgroundColor:"#EF4040",messageColor:"#ffffff",iconUrl:"./img/x-octagon.svg",timeout:1e4,closeOnClick:!0})},close(){try{u.hide({},document.querySelector(".iziToast"))}catch{}}};
//# sourceMappingURL=index.js.map
